funds:
  - shist  
  - sbind
  - scdnt
  - scdrm
  - scont
  - sghum
  - slanf
  - smemb
  - sp&pa
  - sfren
  - sgper
  - slang
  - sprof
  - sspan
  - ssocw
  - scrce
  - scrcl
  - seduc
  - slref
  - senvi
  - sgeog
  - sgeol
  - smath
  - sphys
  - sdaap
  - sbiol
  - schem
  - sarch
  - sdocs
  - sccm
  - sgerm
  - sslav
  - scrmj
  - shums
  - spsyc
  - ssoci
  - scoma
  - sengl
  - sling
  - sthtr
  - safro
  - santh
  - sasia
  - shist
  - sjuda
  - slata
  - sphil
  - spols
  - swoms
  - scas
  - scomp
  - sengr
  - sbusa
  - secon
  - halhs
  - hhgms
  - hhgps
  - hhgps
  - hhlos
  - hhrcs
  - hngs
  - hnles
  - hphs
  - hygs
  - hyss
  - ysems
  - ysmgs
  - yells
  - yoess
  - ylecs
  - yurbs
  - ybots
  - ydays
  - yters
