serial_funds:
  - shist  
  - sbind
  - scdnt
  - scdrm
  - scont
  - sghum
  - slanf
  - smemb
  - sp&pa
  - sfren
  - sgper
  - slang
  - sprof
  - sspan
  - ssocw
  - scrce
  - scrcl
  - seduc
  - slref
  - senvi
  - sgeog
  - sgeol
  - smath
  - sphys
  - sdaap
  - sbiol
  - schem
  - sarch
  - sdocs
  - sccm
  - sgerm
  - sslav
  - scrmj
  - shums
  - spsyc
  - ssoci
  - scoma
  - sengl
  - sling
  - sthtr
  - safro
  - santh
  - sasia
  - shist
  - sjuda
  - slata
  - sphil
  - spols
  - swoms
  - scas
  - scomp
  - sengr
  - sbusa
  - secon
  - halhs
  - hhgms
  - hhgps
  - hhgps
  - hhlos
  - hhrcs
  - hngs
  - hnles
  - hphs
  - hygs
  - hyss
  - ysems
  - ysmgs
  - yells
  - yoess
  - ylecs
  - yurbs
  - ybots
  - ydays
  - yters
selectors_by_fund:
  { aaaaa: "Admin",
    none: "Admin",
    sbind: "Admin",
    scdnt: "Admin",
    scdrm: "Admin",
    scont: "Admin",
    sghum: "Admin",
    slanf: "Admin",
    smemb: "Admin",
    sp&pa: "Admin",
    ubind: "Admin",
    uchin: "Admin",
    ucont: "Admin",
    ughum: "Admin",
    ugsos: "Admin",
    ushlr: "Admin",
    vnbio: "Admin",
    wcarl: "Admin",
    wrref: "Admin",
    xcjgs: "Admin",
    ynedt: "Admin",
    sgper: "Admin",

    sfren: "Arlene",
    slang: "Arlene",
    sspan: "Arlene",
    ufren: "Arlene",
    uspan: "Arlene",
    vfaux: "Arlene",
    yhfru: "Arlene",
    ysivt: "Arlene",
    vlabs: "Arlene",
    ulang: "Arlene",

    ssocw: "Charlie",

    scrce: "Cheryl",
    scrcl: "Cheryl",
    seduc: "Cheryl",
    ucrce: "Cheryl",
    ucrcl: "Cheryl",
    ueduc: "Cheryl",
    vcrcl: "Cheryl",

    callh: "Clermont",
    cbhum: "Clermont",
    cbind: "Clermont",
    cbiol: "Clermont",
    cblaw: "Clermont",
    cbnur: "Clermont",
    cbref: "Clermont",
    cbus: "Clermont",
    ccat: "Clermont",
    cchem: "Clermont",
    ccom: "Clermont",
    ceduc: "Clermont",
    ceng: "Clermont",
    cenvi: "Clermont",
    cgen: "Clermont",
    cgref: "Clermont",
    chist: "Clermont",
    claw: "Clermont",
    clib: "Clermont",
    cmfm: "Clermont",
    cnhum: "Clermont",
    conl: "Clermont",
    cper: "Clermont",
    cser: "Clermont",
    csoc: "Clermont",
    csref: "Clermont",

    sprof: "Debbie",
    uprof: "Debbie",
    slref: "Debbie",
    ulref: "Debbie",

    senvi: "Holly",
    sgeog: "Holly",
    sgeol: "Holly",
    ugeol: "Holly",
    ybalu: "Holly",
    yrich: "Holly",

    ysebu: "Jacquie",
    yseci: "Jacquie",
    ysehi: "Jacquie",
    ysems: "Jacquie",
    ysemt: "Jacquie",
    ysemu: "Jacquie",
    ysepi: "Jacquie",
    ysmgs: "Jacquie",
    ysmgu: "Jacquie",

    sdaap: "Jen",
    udaap: "Jen",
    xcars: "Jen",

    smath: "Jim",
    umath: "Jim",

    yells: "Jim Cummins",

    sarch: "Kevin",
    uarch: "Kevin",

    mbdh: "Law",
    mcarm: "Law",
    mcnll: "Law",
    mcnp: "Law",
    mcont: "Law",
    mdata: "Law",
    mdins: "Law",
    mdorn: "Law",
    mform: "Law",
    mkond: "Law",
    mmorg: "Law",
    mnbav: "Law",
    mnbf: "Law",
    mnbg: "Law",
    mnbks: "Law",
    mnipp: "Law",
    morgg: "Law",
    morgs: "Law",
    mprof: "Law",
    msego: "Law",
    mspec: "Law",
    mwald: "Law",
    mwarm: "Law",

    halhm: "Leslie - HSL",
    halhs: "Leslie - HSL",
    hchil: "Leslie - HSL",
    hhbea: "Leslie - HSL",
    hhda: "Leslie - HSL",
    hhdad: "Leslie - HSL",
    hhgbd: "Leslie - HSL",
    hhgif: "Leslie - HSL",
    hhgm: "Leslie - HSL",
    hhgmc: "Leslie - HSL",
    hhgms: "Leslie - HSL",
    hhgmw: "Leslie - HSL",
    hhgpa: "Leslie - HSL",
    hhgpc: "Leslie - HSL",
    hhgpd: "Leslie - HSL",
    hhgpe: "Leslie - HSL",
    hhgpm: "Leslie - HSL",
    hhgpr: "Leslie - HSL",
    hhgps: "Leslie - HSL",
    hhgpv: "Leslie - HSL",
    hhgpw: "Leslie - HSL",
    hhhm: "Leslie - HSL",
    hhhoa: "Leslie - HSL",
    hhhra: "Leslie - HSL",
    hhhrm: "Leslie - HSL",
    hhill: "Leslie - HSL",
    hhla: "Leslie - HSL",
    hhlm: "Leslie - HSL",
    hhlos: "Leslie - HSL",
    hhrcm: "Leslie - HSL",
    hhrcs: "Leslie - HSL",
    hngc: "Leslie - HSL",
    hngd: "Leslie - HSL",
    hnge: "Leslie - HSL",
    hngs: "Leslie - HSL",
    hnles: "Leslie - HSL",
    hphd: "Leslie - HSL",
    hphs: "Leslie - HSL",
    hrepl: "Leslie - HSL",
    huchm: "Leslie - HSL",
    hygs: "Leslie - HSL",
    hyss: "Leslie - HSL",
    nbiol: "Leslie - Biol",
    sbiol: "Leslie - Biol",
    ubiol: "Leslie - Biol",
    vbiol: "Leslie - Biol",

    sdocs: "Lorna",
    udocs: "Lorna",
    ynblt: "Lorna",
    yndcu: "Lorna",

    sccm: "Mark",
    uccm: "Mark",
    vccbi: "Mark",
    vccfi: "Mark",
    vcchi: "Mark",
    vccm: "Mark",
    vcnfi: "Mark",
    xccms: "Mark",
    xccmu: "Mark",
    yagmu: "Mark",
    yclcu: "Mark",

    ngerm: "Olya",
    sgerm: "Olya",
    sslav: "Olya",
    ugerm: "Olya",
    uslav: "Olya",
    vgehi: "Olya",
    yhgeu: "Olya",

    scrmj: "Randy",
    shums: "Randy",
    spsyc: "Randy",
    ssoci: "Randy",
    upsyc: "Randy",
    usoc: "Randy",

    scoma: "Rosemary",
    sengl: "Rosemary",
    sling: "Rosemary",
    sthtr: "Rosemary",
    ucoma: "Rosemary",
    uengl: "Rosemary",
    vengl: "Rosemary",

    safro: "Sally",
    santh: "Sally",
    sasia: "Sally",
    shist: "Sally",
    sjuda: "Sally",
    slata: "Sally",
    sphil: "Sally",
    spols: "Sally",
    swoms: "Sally",
    uanth: "Sally",
    uasia: "Sally",
    uhist: "Sally",
    ujuda: "Sally",
    uphil: "Sally",
    upols: "Sally",
    uwoms: "Sally",
    vjuda: "Sally",
    yflou: "Sally",
    ylecs: "Sally",
    ylecu: "Sally",
    ystru: "Sally",
    yucsu: "Sally",
    yurbs: "Sally",
    yurbu: "Sally",

    uphys: "Ted",
    sphys: "Ted",
    ncomp: "Ted",
    scas: "Ted",
    scomp: "Ted",
    sengr: "Ted",
    ucas: "Ted",
    uengr: "Ted",
    uucol: "Ted",
    xvals: "Ted",
    xvalt: "Ted",
    xvalu: "Ted",
    xvenu: "Ted",
    yarmu: "Ted",
    ybots: "Ted",
    ybotu: "Ted",
    ydays: "Ted",
    yters: "Ted",
    yteru: "Ted",
    yucmu: "Ted",
    nchem: "Ted",
    schem: "Ted",
    uchem: "Ted",
    yoess: "Ted",
    yoesu: "Ted",

    rallh: "UCBA",
    rbuse: "UCBA",
    rengl: "UCBA",
    rghs: "UCBA",
    rmic: "UCBA",
    rmul: "UCBA",
    rnurs: "UCBA",
    rser: "UCBA",
    rwc: "UCBA",

    sbusa: "Wahib",
    secon: "Wahib",
    ubusa: "Wahib",
    vbaji: "Wahib",
    vbusa: "Wahib",
    vecji: "Wahib" }
